### ISSUE TITLE
Execução projeto

### ISSUE THREAD

**Issue by oliveiralex** [RafaelSantos22/github-api#1]
Ola Rafael, tudo bem?
Estou corrigindo seu trabalho e ao tentar dar um `npm install`, está ocorrendo um erro ao tentar executar.

Como você está executando seu projeto? Você está usando alguma lib específica?

Abraço

**Comment by RafaelSantos22** [comment]
Opa eu usei o vite, pra iniciar uso o comando npm run dev

**Comment by oliveiralex** [comment]
Muito obrigado Rafael
